name: Build Android APK

on:
  push:
    branches: [ "main", "master" ] # Jalankan otomatis saat ada push ke branch main atau master
  workflow_dispatch: # Izinkan menjalankan manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: 3. Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: 4. Make gradlew executable
        run: chmod +x ./gradlew

      - name: 5. Build debug APK
        run: ./gradlew assembleDebug

      - name: 6. Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
